[project]
name = "stdict"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=0.4.1",
    "mcp[cli]>=1.6.0",
    "requests>=2.32.3",
]
